const baseProdutos=[
{nome:'Chaveiro Personalizado',cat:'Chaveiros',preco:'15,00',desc:'Com nome, logo, personagem, time ou tema especial.',emoji:'🔑'},
{nome:'Luminária em LED 3D',cat:'Decoração',preco:'79,90',desc:'Peça decorativa personalizada com iluminação.',emoji:'💡'},
{nome:'Porta Copo Personalizado',cat:'Brindes',preco:'29,90',desc:'Ideal para presentes, empresas e datas especiais.',emoji:'🥤'},
{nome:'Lembrancinha Personalizada',cat:'Lembrancinhas',preco:'8,00',desc:'Ótima para festas, casamentos, aniversários e eventos.',emoji:'🎁'},
{nome:'Decoração com Nome',cat:'Decoração',preco:'49,90',desc:'Nome, inicial ou frase personalizada para decorar.',emoji:'❤️'},
{nome:'Organizador de Mesa',cat:'Organizadores',preco:'39,90',desc:'Produto útil para escritório, estudo e home office.',emoji:'🖊️'},
{nome:'Topo de Bolo 3D',cat:'Festas',preco:'24,90',desc:'Topo personalizado para deixar a comemoração especial.',emoji:'🎂'},
{nome:'Brinde Empresarial',cat:'Brindes',preco:'19,90',desc:'Produtos com logo para sua marca ou empresa.',emoji:'🏢'}];
function getProdutos(){try{return JSON.parse(localStorage.getItem('mjkProdutos'))||baseProdutos}catch(e){return baseProdutos}}
function money(v){return `R$ ${v}`}
function render(){const grid=document.getElementById('gridProdutos'); if(!grid)return; const busca=(document.getElementById('busca').value||'').toLowerCase(); const cat=document.getElementById('categoria').value; const produtos=getProdutos(); const cats=[...new Set(produtos.map(p=>p.cat))]; const sel=document.getElementById('categoria'); if(sel.options.length===1)cats.forEach(c=>sel.insertAdjacentHTML('beforeend',`<option>${c}</option>`)); grid.innerHTML=produtos.filter(p=>(cat==='todos'||p.cat===cat) && (p.nome.toLowerCase().includes(busca)||p.desc.toLowerCase().includes(busca)||p.cat.toLowerCase().includes(busca))).map(p=>`<article class="card"><div class="thumb">${p.img?`<img src="${p.img}" alt="${p.nome}" style="max-width:100%;height:100%;object-fit:cover;width:100%">`:p.emoji}</div><div class="cardBody"><h3>${p.nome}</h3><p>${p.desc}</p><span class="price">A partir de ${money(p.preco)}</span><a class="details" target="_blank" href="https://wa.me/5541988347653?text=Ol%C3%A1%2C%20quero%20or%C3%A7amento%20do%20produto%3A%20${encodeURIComponent(p.nome)}">Ver detalhes</a></div></article>`).join('')}
document.getElementById('busca')?.addEventListener('input',render);document.getElementById('categoria')?.addEventListener('change',render);document.getElementById('menuBtn')?.addEventListener('click',()=>document.getElementById('nav').classList.toggle('open'));render();
